name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  library-darwin:
    runs-on: macos-13
    name: Test Library (Darwin)
    steps:
      - uses: actions/checkout@v3
      - name: Select Xcode 15.0.1
        run: sudo xcode-select -s /Applications/Xcode_15.0.1.app
      - name: Run tests
        run: swift test

  library-windows:
      runs-on: windows-latest
      name: Test Library (Windows)
      steps:
        # We use BCNY's repo since they have newer builds of Swift
        # which have fixed libcurl in Foundation.
        - uses: compnerd/gha-setup-swift@main
          with:
            release-tag-name: "20231203.0"
            github-repo: "thebrowsercompany/swift-build"
            release-asset-name: installer-amd64.exe
            github-token: ${{ secrets.GITHUB_TOKEN }}
        - uses: actions/checkout@v3
        - name: Run Tests
          run: swift test